import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Braces, GitBranch, ScanLine, Target, ShieldCheck, Repeat2, ArrowDown, Sparkles, Terminal, Check } from 'lucide-react';
import { Arrow, Label, FestivalCard, ErrorBox } from '../components/UI.jsx';
import { request, remember } from '../services/api.js';
const features = [ [ScanLine, 'Your resume. Your questions.', 'Real projects, actual skills, and the role you want. That’s where every interview starts.'], [GitBranch, 'Follow-ups with a purpose.', 'Your answer shapes the next question. A little uncertainty? We’ll dig into it.'], [Target, 'Feedback, without the fluff.', 'Technical scoring, clear gaps, and a useful explanation of what you missed.'], [Braces, 'Find your blind spots.', 'See the concepts that need attention. Less guessing, more deliberate practice.'], [Repeat2, 'A smarter next session.', 'Come back to an interview that puts your weakest topics first.'], [ShieldCheck, 'Open weights. More control.', 'Run Gemma locally. Keep your context close and choose your own model.'] ];
export default function Home() {
  const navigate = useNavigate(); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function demo() { setBusy(true); setError(''); try {const s = await request('/interviews/demo', {method: 'POST'}); remember(s); navigate(`/interview/${s.interviewId}`);} catch(e) {setError(e.message); setBusy(false);} }
  return <main id="main">
    <section className="hero wrap"><div className="hero-copy"><Label><span className="status-dot"/> BUILT FOR A FRIEND <span className="label-divider">/</span> OPEN TO EVERYONE</Label><h1>Practice the<br/>interview,<br/><span>not the<br className="desktop-break"/> question bank.</span></h1><p className="hero-description">Your projects. Your skills. Your next role.<br/>An interview built around <strong>you.</strong></p><div className="hero-actions"><Link to="/practice" className="button coral">Start practicing <Arrow diagonal/></Link><button className="text-button" onClick={demo} disabled={busy}>{busy ? 'Building demo…' : 'Try a demo interview'}<Arrow/></button></div><ErrorBox message={error}/><div className="hero-footnote"><span className="tiny-grid">✳</span><span>POWERED BY GEMMA. MADE FOR REAL PROGRESS.</span></div></div>
    <div className="hero-art"><div className="art-caption"><span>LESS MEMORIZATION. MORE UNDERSTANDING.</span><ArrowDown size={16}/></div><div className="interview-preview"><div className="preview-header"><Label><span className="status-dot"/> TECHNICAL INTERVIEW</Label><span className="mono">03 / 07</span></div><div className="preview-content"><div className="preview-tags"><span>AUTHENTICATION</span><span>MEDIUM ↗</span></div><h2>“You built authentication with JWT.<br/>Where would you store the token, and why?”</h2><div className="answer-lines"><span/><span/><span/></div><div className="preview-score"><div><Label>YOUR ANSWER</Label><p><Check size={15}/> A good starting point.</p></div><strong>7.8<span>/10</span></strong></div></div><div className="preview-followup"><Label><GitBranch size={16}/> LET'S GO ONE LEVEL DEEPER</Label><p>“What changes if your application<br/>becomes vulnerable to CSRF?”</p></div><div className="preview-bottom"><span>THINK IT THROUGH.</span><Arrow/></div></div><div className="art-bottom"><span className="demo-stamp">NO TWO RESUMES.<br/>NO TWO INTERVIEWS.</span><span className="pixel-spark">✳</span><span className="art-number">[ 001 — ∞ ]</span></div></div></section>
    <div className="manifesto-strip"><div className="wrap"><span><span className="strip-cross">✳</span> LESS CRAMMING</span><span><span className="strip-cross">✳</span> BETTER QUESTIONS</span><span><span className="strip-cross">✳</span> REAL FEEDBACK</span><span><span className="strip-cross">✳</span> OPEN-WEIGHT AI</span></div></div>
    <section id="how-it-works" className="section wrap"><div className="section-heading"><div><Label>01 / THE PROCESS</Label><h2>From resume to<br/><span className="coral-text">real practice.</span></h2></div><p>No endless question lists.<br/>Just a little context, and an interviewer<br/>who knows where to start.</p></div><div className="steps-grid">{[{title: 'Bring your story.', text: 'Add your resume, target role, and job description. Give us something real to work with.', footer: 'YOUR EXPERIENCE →', icon: <ScanLine/>}, {title: 'Think on your feet.', text: 'Face questions about your projects and decisions. Explain the why, not just the what.', footer: 'A PERSONALIZED INTERVIEW →', icon: <Terminal/>}, {title: 'Know what’s next.', text: 'Get honest feedback, find your weak spots, and build a next session around them.', footer: 'YOUR NEXT STEP →', icon: <Target/>}].map((s, i) => <FestivalCard className={`step-card step-${i}`} key={s.title}><div className="step-top"><span className="step-number">0{i + 1}</span><span className="step-icon">{s.icon}</span></div><h3>{s.title}</h3><p>{s.text}</p><Label className="step-footer">{s.footer}</Label></FestivalCard>)}</div></section>
    <section className="pressure-section"><div className="wrap pressure-grid"><div><Label><span className="status-dot"/> PRESSURE MODE</Label><h2>One answer.<br/><span>Three questions<br/>deeper.</span></h2><p>The real interview starts when someone asks “why.” PalForge spots uncertainty and follows the thread—with up to two follow-ups per question.</p><Link to="/practice?style=pressure" className="button paper-button">Try pressure mode <Arrow diagonal/></Link><div className="pressure-note">A LITTLE PRESSURE. A LOT OF PROGRESS.</div></div><div className="dialogue"><div className="dialogue-card"><Label>INTERVIEWER <span>01</span></Label><p>“You said MongoDB was better for your project. Why?”</p></div><div className="dialogue-card candidate"><Label>YOU</Label><p>“Because its schema is flexible…”</p></div><div className="dialogue-card"><Label>INTERVIEWER <span>02</span></Label><p>“What happens when you need complex joins?”</p></div><div className="dialogue-card final"><Label><GitBranch size={15}/> FOLLOWING THE THREAD <span>03</span></Label><p>“So why didn’t you choose PostgreSQL?”</p></div></div></div></section>
    <section className="section wrap"><div className="section-heading"><div><Label>02 / BUILT TO BE USEFUL</Label><h2>Small project.<br/>Useful features.</h2></div><span className="section-side-note">NO EXTRA NOISE.<br/>JUST BETTER PREPARATION. ↙</span></div><div className="features-grid">{features.map(([Icon, title, text], i) => <article className="feature-card" key={title}><div className="feature-top"><Icon size={27}/><span className="mono">0{i + 1}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section id="about" className="story-section"><div className="wrap story-grid"><div><Label>03 / WHY I BUILT IT</Label><h2>Generic interview tools<br/>didn’t know<br/><span className="coral-text">my friend.</span></h2></div><div className="story-copy"><p>My friend was preparing for software engineering placements. He had projects to talk about and skills on his resume. But every practice platform gave him the same hundred questions.</p><p>None asked why <em>he</em> chose MongoDB. Or how <em>his</em> authentication worked. Or what the company actually needed.</p><p className="story-punchline">So I built PalForge.</p><Label>ONE FRIEND. ONE TARGET ROLE. A BETTER WAY TO PREPARE.</Label></div></div></section>
    <section className="section wrap open-grid"><div><Label>04 / WHY OPEN?</Label><h2>Your resume<br/>shouldn’t need<br/>a <span className="coral-text">black box.</span></h2><p className="open-copy">Gemma is PalForge’s open-weight intelligence layer. Local inference means you control where your resume goes, how the interviewer behaves, and which model runs the show.</p><div className="open-benefits"><span><Check size={16}/> Local inference</span><span><Check size={16}/> Model flexibility</span><span><Check size={16}/> No per-question API fees</span><span><Check size={16}/> No vendor lock-in</span></div></div><FestivalCard className="architecture"><Label>THE STACK, WITHOUT THE MYSTERY</Label><div className="architecture-input"><span>YOUR RESUME</span><span>+ TARGET ROLE</span><span>+ JOB DESCRIPTION</span></div><ArrowDown/><div className="architecture-node">PALFORGE <small>REACT UI + NODE API</small></div><ArrowDown/><div className="architecture-node gemma-node"><Sparkles size={21}/> GEMMA <small>OPEN-WEIGHT INTELLIGENCE</small></div><ArrowDown/><div className="architecture-node">YOUR INTERVIEW <small>QUESTIONS → FEEDBACK → NEXT SESSION</small></div><div className="architecture-db">MONGODB ATLAS / LOCAL FILES<br/><span>Session history + weakness profile</span></div></FestivalCard></section>
    <section className="technology wrap"><Label>BUILT WITH / NOT SPONSORED BY</Label><div>{['Gemma', 'React', 'Node.js', 'Express', 'MongoDB Atlas', 'Render', 'Ollama', 'GitHub'].map(name => <span key={name}>{name}</span>)}</div></section>
    <section className="final-cta wrap"><div><Label>YOUR TURN</Label><h2>Ready for the question<br/>after the question?</h2><p>Built for Hacktoberfest 2026 · Build for a Friend</p></div><Link to="/practice" className="button paper-button">Start your interview <Arrow diagonal/></Link><span className="cta-spark" aria-hidden="true">✳</span></section>
  </main>;
}
