import { useEffect, useState } from 'react';
import { ArrowUpRight, ArrowRight, X, Menu, Anvil, Check, AlertCircle } from 'lucide-react';
import { Link, NavLink } from 'react-router-dom';
export const Arrow = ({diagonal = false, ...props}) => diagonal ? <ArrowUpRight size={19} {...props}/> : <ArrowRight size={19} {...props}/>;
export function Brand() { return <Link to="/" className="brand" aria-label="PalForge home"><Anvil size={29} strokeWidth={2.3}/><span>PALFORGE<span className="brand-dot" aria-hidden="true">✳</span></span></Link>; }
export function Navbar() {
  const [open, setOpen] = useState(false);
  return <header className="header"><div className="nav-wrap"><div className="brand-group"><Brand/><span className="build-tag">HF26 BUILD</span></div><button className="menu-button" onClick={() => setOpen(!open)} aria-expanded={open} aria-label={open ? 'Close navigation' : 'Open navigation'}>{open ? <X/> : <Menu/>}</button><nav aria-label="Main navigation" className={open ? 'nav-links open' : 'nav-links'} onClick={() => setOpen(false)}><NavLink to="/" end>Home</NavLink><Link to="/#how-it-works">How it works</Link><NavLink to="/practice">Practice</NavLink><NavLink to="/progress">Progress</NavLink><Link to="/#about">About</Link><Link className="button coral nav-cta" to="/practice">Start interview <Arrow diagonal/></Link></nav></div></header>;
}
export function Footer() { return <footer className="footer"><div className="footer-top"><Brand/><p>One friend. One target role.<br/>One interview that matters.</p><Link to="/practice" className="footer-link">Go make yourself ready <Arrow diagonal/></Link></div><div className="footer-bottom"><span>BUILT FOR A FRIEND. OPEN TO EVERYONE.</span><span>HF26 WEEKEND BUILD · OPEN SOURCE · MIT</span><span>© 2026 PALFORGE</span></div></footer>; }
export function Label({children, className = ''}) { return <div className={`eyebrow ${className}`}>{children}</div>; }
export function FestivalCard({children, className = '', ...props}) { return <div className={`festival-card ${className}`} {...props}>{children}</div>; }
export function ErrorBox({message}) { return message ? <div className="error-box" role="alert"><AlertCircle size={20}/><span>{message}</span></div> : null; }
export function LoadingInterview({title = 'Forging your interview.'}) {
  const labels = ['Reading your projects…', 'Matching skills with the role…', 'Finding areas worth questioning…', 'Preparing your interviewer…'];
  const [step, setStep] = useState(0);
  useEffect(() => { const timer = setInterval(() => setStep(v => (v + 1) % labels.length), 2200); return () => clearInterval(timer); }, []);
  return <div className="loading-panel" role="status" aria-live="polite"><Anvil size={45}/><Label>A LITTLE CONTEXT. A BETTER INTERVIEW.</Label><h2>{title}</h2><p>{labels[step]}</p><div className="loading-blocks">{labels.map((l, i) => <span key={l} className={i <= step ? 'active' : ''}/>)}</div><small>Local models can take a minute. Keep this page open.</small></div>;
}
export function SkillBar({topic, score}) { return <FestivalCard className="skill-card"><div><h3>{topic}</h3><strong>{score}<small>/100</small></strong></div><div className="skill-track" role="meter" aria-label={`${topic} score`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={score}><span style={{width: `${score}%`}} className={score < 70 ? 'low' : ''}/></div><Label>{score >= 70 ? 'SOLID FOUNDATION' : 'PRACTICE NEXT'}</Label></FestivalCard>; }
export function ProgressStrip({current, total}) { return <div className="progress-strip"><div><Label>YOUR INTERVIEW</Label><span className="mono">{String(current).padStart(2, '0')} / {String(total).padStart(2, '0')}</span></div><div className="progress-track" role="progressbar" aria-label="Interview progress" aria-valuemin={0} aria-valuemax={total} aria-valuenow={current}><span style={{width: `${current / total * 100}%`}}/></div></div>; }
export function EvaluationPanel({evaluation, onContinue, label}) { return <FestivalCard className="evaluation-panel"><div className="evaluation-head"><Label>THE INTERVIEWER'S TAKE</Label><strong>{evaluation.score.toFixed(1)}<small> / 10</small></strong></div><div className="evaluation-grid"><div><Label>WHAT LANDED</Label>{evaluation.strengths.length ? evaluation.strengths.map(s => <p key={s}><Check size={16}/>{s}</p>) : <p>No clear strengths yet. Keep practicing.</p>}</div><div><Label>GO A LEVEL DEEPER</Label>{evaluation.missingPoints.length ? evaluation.missingPoints.map(s => <p key={s}><Arrow size={16}/>{s}</p>) : <p>No major gaps identified.</p>}</div></div><div className="interviewer-note"><Label>INTERVIEWER NOTE</Label><p>{evaluation.feedback}</p></div>{evaluation.followUpRequired && <div className="followup-preview"><Label>FOLLOW-UP QUESTION</Label><p>{evaluation.followUpQuestion}</p></div>}<button className="button coral" onClick={onContinue}>{label}<Arrow/></button></FestivalCard>; }
